language: node_js
node_js:
  - "6.2.2"
before_install:
  - npm install -g eslint@3.10.2 eslint-config-airbnb@13.0.0 eslint-plugin-jsx-a11y@2.2.3 eslint-plugin-import@2.2.0 eslint-plugin-react@6.7.1
  - eslint *
branches:
  only:
    - master
